version: "3.8"
services:
  web:
    build: .
    ports:
      - 8080:8080
    restart: always
    env_file: .env
    depends_on:
      - db
    volumes:
      - .:/go/src/github.com/kanban/
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: kanban
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    restart: always
    volumes:
      - ./infrastructure/migrations/:/docker-entrypoint-initdb.d/
      - ./postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@kanban.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - db
    ports:
      - 5050:80
    restart: unless-stopped